feat: add form constraints story
Thinkful-Ed/starter-restaurant-reservation pull request #2
Opened 2021-01-27 08:12 UTC by kchia

2021-02-03 05:54 UTC, kchia commented
My hunch is that for the average student, this user story is probably going to take at least 2 days.

2021-02-03 15:48 UTC, dalelotts requested changes
Just a few minor changes. The backend validation is missing entirely so the API will still accept invalid reservations. As always, both frontend and backend validation much exist.

2021-02-03 15:48 UTC, dalelotts commented on front-end/src/reservations/ReservationCreate.js
> +      .then(savedReservation => {
This change violates the Prettier coding standard and will get reverted as soon as someone runs prettier on this code.

2021-02-03 15:48 UTC, dalelotts commented on front-end/src/utils/generateInvalidTime.js
> +  let hour = Math.floor(time / 60);
should be const

2021-02-03 15:48 UTC, dalelotts commented on front-end/src/utils/generateInvalidTime.js
> +  let minutes = time % 60;
should be const

2021-02-03 15:48 UTC, dalelotts commented on front-end/src/utils/generateInvalidTime.js
> +import { RESTAURANT_SCHEDULE } from "../reservations/constants";
This file should be in `__test__/utils` and comments that it is for test use only. If you give the student the desired open and close time there is no need for this code.

2021-02-03 15:48 UTC, dalelotts commented on front-end/src/utils/generateNextDate.js
> +export default function generateNextDate(working = true) {
same as above

2021-02-03 15:48 UTC, dalelotts commented on front-end/src/utils/generateValidTime.js
> +
same as above

2021-02-03 15:51 UTC, dalelotts commented
I'll also add that the frontend validation can reasonably be  limited restricting input to open dates/hours only - which will be much easier. make use of min/max attributes rather than writing code. You can delegate to the backend for validation that requires code.

2021-02-03 15:56 UTC, dalelotts requested changes

2021-02-03 15:56 UTC, dalelotts commented on README.md
> +so that my customers can only make a reservation during eligible days and times
I want to prevent users from creating reservations before we open or within XX minutes before closing

2021-02-03 18:30 UTC, dalelotts commented
we need to have the ability to run unit and e2e tests so the e2e tests are in the e2e directory.
 
 Can you also restore the App test?

2021-02-04 06:46 UTC, kchia commented
@dalelotts what is App.test needed for?

2021-02-04 07:12 UTC, kchia commented on front-end/src/utils/generateInvalidTime.js
> +import { RESTAURANT_SCHEDULE } from "../reservations/constants";
Would that be a bit too "constraining"?

2021-02-04 07:18 UTC, kchia commented on README.md
> +so that my customers can only make a reservation during eligible days and times
Hmm...the example provided above does not adequately describe the user story, so I'm going to stick with my original version with some minor updates.

2021-02-04 20:02 UTC, dalelotts commented on front-end/package.json
> +    "test:unit": "react-scripts test --testPathIgnorePatterns=src/__tests__/utils",
Is there some reason these cannot be moved to /e2e?

2021-02-04 20:05 UTC, kchia commented
Moving these as we speak.
ᐧ

On Thu, Feb 4, 2021 at 10:03 AM Dale Lotts <notifications@github.com> wrote:

> *@dalelotts* commented on this pull request.
> ------------------------------
>
> In front-end/package.json
> <https://github.com/Thinkful-Ed/starter-restaurant-reservation/pull/2#discussion_r570508168>
> :
>
> > @@ -25,7 +26,7 @@
>      "start:frontend": "npx cross-env BROWSER=none NODE_ENV=test react-scripts start",
>      "build": "react-scripts build",
>      "test": "npx cross-env CI=true run-s test:unit test:e2e",
> -    "test:unit": "react-scripts test ",
> +    "test:unit": "react-scripts test --testPathIgnorePatterns=src/__tests__/utils",
>
> Is there some reason these cannot be moved to /e2e?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Thinkful-Ed/starter-restaurant-reservation/pull/2#pullrequestreview-583767521>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB3KSMXEEMMBYTQU3PJUEHDS5L4P7ANCNFSM4WU2GQDA>
> .
>

2021-02-04 23:55 UTC, kchia commented on README.md
> +### US-3 Create reservation within eligible timeframe
@dalelotts I ultimately ended up separating the user stories vertically instead...

2021-02-05 00:22 UTC, dalelotts commented on front-end/package.json
> +    "test:unit": "react-scripts test --testPathIgnorePatterns=e2e/utils",
Is this needed? I don't think /e2e is in the default search path.

2021-02-05 07:33 UTC, kchia commented on front-end/package.json
> +    "test:unit": "react-scripts test --testPathIgnorePatterns=e2e/utils",
Not needed anymore.

2021-02-08 23:25 UTC, merged